name: Lunsjkollektivet menu slack action
description: Posts the next working day's menu from Lunsjkollektivet to a Slack channel
inputs:
    slack_webhook:
        description: >
            Slack webhook URL.
        required: true
    slack_channel:
        description: >
            Slack channel to post to.
        required: true
    slack_author:
        description: >
            Slack author name.
        required: true
    slack_skip_sending_message:
        description: >
            Set to true to skip sending the message to Slack. Used for testing.
        required: false
runs:
    using: node12
    main: dist/index.js
branding:
    icon: sunrise
    color: yellow
